repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop]
      - id: check-added-large-files
        args: [--maxkb=45000]
      - id: check-ast
        files: modi/*
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: name-tests-test
      - id: forbid-new-submodules
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        files: modi/*
        language_version: python3.6
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        files: modi/*
        language_version: python3.6
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        files: modi/*
        language_version: python3.6
  - repo: local
    hooks:
      - id: unit-test
        name: unit test
        entry: python -m unittest discover
        language: system
        types: [python]
        files: tests/*
